version: "3.9"
services:
  discordbot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
     - CONFIG.env
  mongo:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped

volumes:
  mongodb_data_container:
