version: "3.9"
services:
  discordbot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
     - CONFIG.env
  mongo:
    image: 'webhippie/mongodb:latest'
    environment:
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: rootpassword
      MONGODB_USERNAME: root
      MONGODB_NOAUTH: "true"
      MONGODB_VERBOSE: "true"
    volumes:
      - mongodb_data_container:/var/lib/mongodb
    restart: unless-stopped

volumes:
  mongodb_data_container:
